name: driveit_refactored
description: "DriveIt - Car Management App (Refactored)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  
  # Database
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  
  # DI
  get_it: ^7.6.0
  injectable: ^2.3.0
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Navigation
  go_router: ^12.0.0
  
  # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.17.0
  uuid: ^4.1.0
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  
  # Backend
  supabase_flutter: ^2.0.0
  
  # Charts
  fl_chart: ^1.1.1
  
  # Image compression
  flutter_image_compress: ^2.0.4
  
  # Local notifications
  flutter_local_notifications: ^17.2.2
  
  # Path
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  drift_dev: ^2.13.0
  
  # Testing
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  
  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/